server:
  port: 8080
  address: 0.0.0.0
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 73313302339-6n60o5d8tu1nven2skog096s71q1v1uk.apps.googleusercontent.com
            client-secret: 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
            scope: profile

          naver:
            client-id: AHSvGG08WqlsCX1gF8gI
            client-secret: cSR2Z5tdzf
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name
            client-name: Naver

          kakao:
            client-id: f0cfd8fd7bb4da57b220043a25208ca7
            client-secret: H5gJCOSIRX7Rfmwwoj9Ce9MOxkpsSYSU
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
#local mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/timetogether?serverTimezone=UTC&characterEncoding=UTF-8
    username: root

  jpa:
    hibernate:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secretKey: WkdGN2tMZE9qM3RyTDRqYVhPZG5uV2t5QlJGV3VwREl1TFdGbFJXVlR3WkhwdldhQ1JX

  access:
    expiration: 3600000 # 1??(60?) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> ??) * 14(2?))
    header: Authorization-refresh

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

debug: true
